<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AddPack.DataAccess\AddPack.DataAccess.csproj" />
    <ProjectReference Include="..\AddPack.Models\AddPack.Models.csproj" />
    <ProjectReference Include="..\AddPack.Utility\AddPack.Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\IServices\" />
  </ItemGroup>

</Project>
