// <auto-generated />
using System;
using AddPack.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddPack.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923181223_InitializeDb")]
    partial class InitializeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddPack.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Inne.",
                            IsActive = true,
                            Name = "Inne",
                            Slug = "inne",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Namioty turystyczne i bushcraftowe na każdą pogodę.",
                            IsActive = true,
                            Name = "Namioty",
                            Slug = "namioty",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plecaki trekkingowe i miejskie w budżetowych cenach.",
                            IsActive = true,
                            Name = "Plecaki",
                            Slug = "plecaki",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Odzież funkcjonalna do aktywności na świeżym powietrzu.",
                            IsActive = true,
                            Name = "Odzież outdoorowa",
                            Slug = "odziez-outdoorowa",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kuchenki, naczynia i akcesoria do gotowania w terenie.",
                            IsActive = true,
                            Name = "Kuchnia turystyczna",
                            Slug = "kuchnia-turystyczna",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lekkie namioty solo do szybkich wypraw.",
                            IsActive = true,
                            Name = "Namioty 1-osobowe",
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Slug = "namioty-1-osobowe",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Przestronne namioty dla 4-6 osób.",
                            IsActive = true,
                            Name = "Namioty rodzinne",
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Slug = "namioty-rodzinne",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plecaki 40-65L na wielodniowe wyprawy.",
                            IsActive = true,
                            Name = "Plecaki trekkingowe",
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Slug = "plecaki-trekkingowe",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Codzienne plecaki do miasta i na uczelnię.",
                            IsActive = false,
                            Name = "Plecaki miejskie",
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Slug = "plecaki-miejskie",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kurtki membranowe odporne na deszcz i wiatr.",
                            IsActive = true,
                            Name = "Kurtki przeciwdeszczowe",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Slug = "kurtki-przeciwdeszczowe",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kompaktowe kuchenki turystyczne na kartusze gazowe.",
                            IsActive = true,
                            Name = "Kuchenki gazowe",
                            ParentId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Slug = "kuchenki-gazowe",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("AddPack.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f3b2d65-17c9-4a82-be31-6d5e7c9042fa"),
                            Brand = "AddPack",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 24, 22, 18, 50, 0, DateTimeKind.Utc),
                            Description = "Zestaw do gotowania na świeżym powietrzu. Składa się z osłony przeciwwiatrowej pełniącej funkcję uchwytu na garnek, palnika alkoholowego, garnka do gotowania, pokrywek do gotowania i wkładki do garnka na akcesoria. Idealny do biwakowania i turystyki pieszej.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Zestaw do gotowania",
                            SeriesId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            Slug = "zestaw-do-gotowania",
                            UpdatedAt = new DateTime(2026, 8, 24, 22, 18, 58, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AddPack.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d92f4b8-3e17-4c65-a081-9f2b7d5e4361"),
                            AltText = "Zestaw do gotowania na świeżym powietrzu - Wersja podstawowa, widok z przodu",
                            CreatedAt = new DateTime(2026, 8, 24, 22, 18, 50, 0, DateTimeKind.Utc),
                            ImageUrl = "wwroot/images/products/c51a7e29-84d3-46f0-9b62-1e5c8a734d09/6d92f4b8-3e17-4c65-a081-9f2b7d5e4361_image.jpg",
                            IsPrimary = true,
                            ProductVariantId = new Guid("c51a7e29-84d3-46f0-9b62-1e5c8a734d09"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a84c1f73-6b29-45d8-90e4-3f7a5c2d8169"),
                            AltText = "Zestaw do gotowania na świeżym powietrzu - Wersja podstawowa, widok z góry",
                            CreatedAt = new DateTime(2026, 8, 24, 22, 18, 58, 0, DateTimeKind.Utc),
                            ImageUrl = "wwroot/images/products/c51a7e29-84d3-46f0-9b62-1e5c8a734d09/a84c1f73-6b29-45d8-90e4-3f7a5c2d8169_image.jpg",
                            IsPrimary = false,
                            ProductVariantId = new Guid("c51a7e29-84d3-46f0-9b62-1e5c8a734d09"),
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("AddPack.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompareAtPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariant");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c51a7e29-84d3-46f0-9b62-1e5c8a734d09"),
                            CompareAtPrice = 150.00m,
                            CostPrice = 100.00m,
                            CreatedAt = new DateTime(2026, 8, 24, 22, 18, 50, 0, DateTimeKind.Utc),
                            Description = "Wersja podstawowa zestawu do gotowania na świeżym powietrzu. Składa się z osłony przeciwwiatrowej pełniącej funkcję uchwytu na garnek, palnika alkoholowego 30ml, garnka do gotowania 1l + 0,25l, pokrywek do gotowania i wkładki do garnka na akcesoria.",
                            IsActive = true,
                            IsFeatured = true,
                            MetaDescription = "Zestaw do gotowania na świeżym powietrzu od AddPack. Idealny do biwakowania i turystyki pieszej. Składa się z osłony przeciwwiatrowej, palnika alkoholowego 30ml, garnka do gotowania 1l + 0,25l, pokrywek i wkładki na akcesoria.",
                            MetaName = "Zestaw do gotowania na świeżym powietrzu podstawowy - AddPack",
                            Name = "Zestaw do gotowania - Wersja podstawowa",
                            Price = 150.00m,
                            ProductId = new Guid("8f3b2d65-17c9-4a82-be31-6d5e7c9042fa"),
                            SKU = "AP-OD-GR-CCK-001",
                            Slug = "wersja-podstawowa",
                            StockQuantity = 5,
                            UpdatedAt = new DateTime(2026, 8, 24, 22, 18, 58, 0, DateTimeKind.Utc),
                            Weight = 180m
                        });
                });

            modelBuilder.Entity("AddPack.Models.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 31, 0, DateTimeKind.Utc),
                            Description = "Demo series for developing the product.",
                            IsActive = true,
                            Name = "Demo",
                            Slug = "demo",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("7b9f5e7c-6d2a-4f18-9a4c-8e2c5d7f1234"),
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 35, 0, DateTimeKind.Utc),
                            Description = "Gear series for outdoor use.",
                            IsActive = true,
                            Name = "Gear",
                            Slug = "gear",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a3f5c2d1-91e4-4c7a-8b23-5d9e1f6a42c8"),
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 37, 0, DateTimeKind.Utc),
                            Description = "Survival series for emergency situations.",
                            IsActive = true,
                            Name = "Survival",
                            Slug = "survival",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("d81e6b42-7c95-4a13-bf68-2e5d9a7c3140"),
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 43, 0, DateTimeKind.Utc),
                            Description = "EDC series for everyday carry.",
                            IsActive = true,
                            Name = "EDC",
                            Slug = "edc",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("f4c82a19-35d7-46e0-91ab-6c3f8e2d7501"),
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 50, 0, DateTimeKind.Utc),
                            Description = "Systems series for comprehensive solutions.",
                            IsActive = true,
                            Name = "Systems",
                            Slug = "systems",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("AddPack.Models.Category", b =>
                {
                    b.HasOne("AddPack.Models.Category", "CategoryParent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoryParent");
                });

            modelBuilder.Entity("AddPack.Models.Product", b =>
                {
                    b.HasOne("AddPack.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddPack.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AddPack.Models.ProductImage", b =>
                {
                    b.HasOne("AddPack.Models.ProductVariant", "ProductVariant")
                        .WithMany("Images")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("AddPack.Models.ProductVariant", b =>
                {
                    b.HasOne("AddPack.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AddPack.Models.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("AddPack.Models.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("AddPack.Models.ProductVariant", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
