// <auto-generated />
using System;
using AddPack.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddPack.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddPack.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CompareAtPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "AddPack",
                            CompareAtPrice = 150.00m,
                            CostPrice = 100.00m,
                            CreatedAt = new DateTime(2026, 8, 24, 22, 18, 50, 0, DateTimeKind.Utc),
                            Description = "Zestaw do gotowania na świeżym powietrzu. Składa się z osłony przeciwwiatrowej pełniącej funkcję uchwytu na garnek, palnika alkoholowego, garnka do gotowania, pokrywek do gotowania i wkładki do garnka na akcesoria. Idealny do biwakowania i turystyki pieszej.",
                            IsActive = true,
                            IsFeatured = true,
                            MetaDescription = "Zestaw do gotowania na świeżym powietrzu od AddPack. Idealny do biwakowania i turystyki pieszej. Składa się z osłony przeciwwiatrowej, palnika alkoholowego, garnka do gotowania, pokrywek i wkładki na akcesoria.",
                            MetaTitle = "Zestaw do gotowania na świeżym powietrzu - AddPack",
                            Name = "Zestaw do gotowania",
                            Price = 150.00m,
                            SKU = "AP-OD-GR-CCK-001",
                            SeriesId = 1,
                            Slug = "zestaw-do-gotowania",
                            UpdatedAt = new DateTime(2026, 8, 24, 22, 18, 58, 0, DateTimeKind.Utc),
                            Weight = 180m
                        });
                });

            modelBuilder.Entity("AddPack.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 31, 0, DateTimeKind.Utc),
                            Description = "Demo series for developing the product.",
                            IsActive = true,
                            Name = "Demo",
                            Slug = "demo",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 35, 0, DateTimeKind.Utc),
                            Description = "Gear series for outdoor use.",
                            IsActive = true,
                            Name = "Gear",
                            Slug = "gear",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 37, 0, DateTimeKind.Utc),
                            Description = "Survival series for emergency situations.",
                            IsActive = true,
                            Name = "Survival",
                            Slug = "survival",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 43, 0, DateTimeKind.Utc),
                            Description = "EDC series for everyday carry.",
                            IsActive = true,
                            Name = "EDC",
                            Slug = "edc",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 24, 22, 17, 50, 0, DateTimeKind.Utc),
                            Description = "Systems series for comprehensive solutions.",
                            IsActive = true,
                            Name = "Systems",
                            Slug = "systems",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("AddPack.Models.Product", b =>
                {
                    b.HasOne("AddPack.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AddPack.Models.Series", b =>
                {
                    b.HasOne("AddPack.Models.Series", "SeriesParentId")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("SeriesParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
